create database prueba_1;

CREATE TABLE CLIENTE(
IdCliente SERIAL,
identificacion int NOT NULL,
nombre varchar(50) NOT NULL,
apellido varchar(50) NOT NULL,
direccion varchar(50) NOT NULL,
telefono varchar(50) NOT NULL,
email varchar(50) NOT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY
(IdCliente));

SELECT * FROM CLIENTE;


CREATE TABLE CATEGORIA(
IdCategoria SERIAL,
nombre varchar(50) NOT NULL,
descripcion varchar(50) NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY
(IdCategoria));

SELECT * FROM CATEGORIA;

CREATE TABLE ORDEN(
IdOrden SERIAL,
IdCliente int NOT NULL,
fecha date,
CONSTRAINT PK_ORDEN PRIMARY KEY (IdOrden),
CONSTRAINT FK_ORDEN FOREIGN KEY (IdCliente) REFERENCES CLIENTE (IdCliente)
);

SELECT * FROM ORDEN;

CREATE TABLE PRODUCTO(
IdProducto SERIAL,
nombre varchar(50) NOT NULL,
precio money,
stock int,
CONSTRAINT PK_PRODUCTO PRIMARY KEY (IdProducto));

SELECT * FROM PRODUCTO;

CREATE TABLE PRODUCTOXCATEGORIA(
IdProxCat SERIAL,
IdCategoria int NOT NULL,
IdProducto int NOT NULL,
CONSTRAINT PK_PROXCAT PRIMARY KEY (IdProxCat),
CONSTRAINT FK_PROXCATCATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA (IdCategoria),
CONSTRAINT FK_PROXCATPRODUCTO FOREIGN KEY (IdProducto) REFERENCES PRODUCTO (IdProducto)
);

SELECT * FROM PRODUCTOXCATEGORIA;

CREATE TABLE DETALLE_ORDENES(
IdDetalle SERIAL,
IdOrden int NOT NULL,
IdProducto int NOT NULL,
cantidad int NOT NULL,
precio money NOT NULL,
CONSTRAINT PK_DETALLE PRIMARY KEY (IdDetalle),
CONSTRAINT FK_DETALLEORDEN FOREIGN KEY (IdOrden) REFERENCES ORDEN (IdOrden),
CONSTRAINT FK_DETALLEPRODUCTODOS FOREIGN KEY (IdProducto) REFERENCES PRODUCTO (IdProducto)
);



